Remove PIDs from harness environment, instead check for sqlite3 and cmail-admin

diff --git a/tests/harness/environment b/tests/harness/environment
--- a/tests/harness/environment
+++ b/tests/harness/environment
@@ -28,6 +28,18 @@ if [ -z "$CMAIL_TEST_ENVIRONMENT_OK" ]; then
 		exit 255
 	fi
 
+	#test for prerequisites
+	if [ -z "$(which sqlite3)" ]; then
+		printf "environment: Need sqlite, aborting\n"
+		exit 255
+	fi
+
+	#test for admin tools
+	if [ -z "$(which cmail-admin-user)" ] || [ -z "$(which cmail-admin-address)" ]; then
+		printf "environment: cmail-admin not found, aborting\n"
+		exit 255
+	fi
+
 	mkdir -p $(dirname "$TEST_MARKER_FILE")
 	
 	#insert the common stuff
@@ -35,9 +47,6 @@ if [ -z "$CMAIL_TEST_ENVIRONMENT_OK" ]; then
 
 	#gather some pids
 	printf "export CMAIL_TEST_ENVIRONMENT_OK=\"%s\"\n" "$(date)" >> "$TEST_MARKER_FILE"
-	printf "export CMAIL_TEST_SMTPD_PID=\"%s\"\n" "$(pidof cmail-smtpd)" >> "$TEST_MARKER_FILE"
-	printf "export CMAIL_TEST_POPD_PID=\"%s\"\n" "$(pidof cmail-popd)" >> "$TEST_MARKER_FILE"
-	printf "export CMAIL_TEST_DISPATCHD_PID=\"%s\"\n" "$(pidof cmail-dispatchd)" >> "$TEST_MARKER_FILE"
 
 	. ./database
 	database_environment_init
@@ -47,19 +56,6 @@ if [ -z "$CMAIL_TEST_ENVIRONMENT_OK" ]; then
 else
 	if [ -n "$CMAIL_TEST_VERBOSE_ENVIRONMENT" ]; then
 		printf "environment: Continuing %s\n" "$CMAIL_TEST_ENVIRONMENT_OK"
-	fi
-
-	if [ -z "$CMAIL_TEST_IGNORE_REALITY" ]; then
-		if [ -z "$CMAIL_TEST_SMTPD_PID" ]; then
-			printf "environment: cmail-smtpd seems not to have been started\n"
-			read dummy < /dev/tty
-		elif [ -z "$CMAIL_TEST_POPD_PID" ]; then
-			printf "environment: cmail-popd seems not to have been started\n"
-			read dummy < /dev/tty
-		elif [ -z "$CMAIL_TEST_DISPATCHD_PID" ]; then
-			printf "environment: cmail-dispatchd seems not to have been started\n"
-			read dummy < /dev/tty
-		fi
 	fi
 fi
 
