Rename cmail-msa to cmail-smtpd
This change more accurately reflects the usage of cmail-msa.
It may break existing installations, so be sure to update all binaries,
init scripts and remember to rename msa.conf to smtpd.conf.

diff --git a/setup/config-helper b/setup/config-helper
--- a/setup/config-helper
+++ b/setup/config-helper
@@ -8,31 +8,15 @@ whiptail(){
 	$WHIPTAIL_BIN "$@" 3>&2 2>&1 1>&3	
 }
 
-init(){
-	if [ ! -f "$CMAIL_MASTER_DB" ]; then
-		printf "Could not find master database - please supply a CMAIL_MASTER_DB environment variable\n"
-		return 1
-	fi
+if [ ! -f "$CMAIL_MASTER_DB" ]; then
+	printf "Could not find master database - please supply a CMAIL_MASTER_DB environment variable\n"
+	exit 2
+fi
 
-	WHIPTAIL_BIN=$(which whiptail)
-	if [ "$?" != "0" ]; then
-		printf "Could not find a working whiptail - please install it\n"
-		return 1
-	fi
+WHIPTAIL_BIN=$(which whiptail)
+if [ "$?" != "0" ]; then
+	printf "Could not find a working whiptail - please install it\n"
+	exit 1
+fi
 
-	return 0
-}
 
-init
-
-while [ "$?" = "0" ]; do
-	ACTION=$(whiptail --title "Initial configuration" --menu "Select an action" 25 78 5 "Add User" "Add a user to the system" "Edit user" "Edit an existing user" "Add address" "Add an address" "Edit address" "Edit an existing address")
-
-	#TODO
-	# User
-	#  - msa/Routing
-	#  - popd access
-	#  Address
-	#  - User mapping
-	#  - Order
-done
